HXUBBS/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

from HXUBBS import settings

favicon_view = RedirectView.as_view(url='/static/imgs/favicon.ico', permanent=True)

# 定制站点头部和标题
admin.site.site_title = '论坛后台管理'  # 站点标题
admin.site.site_header = '论坛后台管理'  # 站点头部

urlpatterns = [
    re_path(r'favicon\.ico$', favicon_view),
    re_path(r'favicon\.png$', favicon_view),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('bbs.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('userinfo.urls')),
    path('likes/', include('likes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/urls.py
from django.urls import path
from bbs.views import *


urlpatterns = [
    path('', index, name='index'),
    path('PostApi', PostList.as_view(), name='PostApi'),
    path('addpost/', addpost),
    path('login/', acc_login, name='login'),
    path('logout/', acc_logout, name='logout'),
    path('register/', register, name='register'),
    path('category/', category, name='category'),
    path('publish/', publish, name='publish'),
    path('categorydetail/', caregorydetail, name='categorydetail'),
    path('postdetail/<int:post_id>', postdetail, name='postdetail'),
    path('linked/', linked, name='linked'),
    path('search/', search, name='search'),
]

bbs/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import format_html
from mdeditor.fields import MDTextField
from django.db import models
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=128, verbose_name='标题')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='版块')
    theme = models.ForeignKey('Theme', on_delete=models.CASCADE)
    content = RichTextUploadingField(verbose_name='帖子内容')
    author = models.ForeignKey('UserProfile', on_delete=models.CASCADE, verbose_name='作者')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modify_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')
    comment_count = models.IntegerField(verbose_name='评论数', default=0)
    read_num = models.IntegerField(verbose_name='点击量', default=0)
    priority = models.IntegerField(verbose_name='是否置顶',default=0)

    class Meta:
        ordering = ['-created_time']
        verbose_name = "帖子"  # 表名改成中文名
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def short_content(self):
        if len(str(self.content)) > 30:
            return '{}...'.format(str(self.content)[0:29])
        else:
            return str(self.content)

    short_content.allow_tags = True
    short_content.short_description = 'content'


class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='版块名')
    image = models.ImageField(upload_to='categoryimg', default='categoryimg/beidouqixing.png')
    brief = models.CharField(max_length=128, default='欢迎查看本版块帖子',  verbose_name='版块简介')
    post_num = models.IntegerField(default=0, verbose_name='帖子数')

    class Meta:

        verbose_name = "版块"  # 表名改成中文名
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Theme(models.Model):
    name = models.CharField(max_length=128, verbose_name='主题')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "主题"  # 表名改成中文名
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Notice(models.Model):
    content = RichTextField(verbose_name='公告信息')

    def __str__(self):
        return self.content


    class Meta:
        verbose_name = "公告"  # 表名改成中文名
        verbose_name_plural = verbose_name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, verbose_name='用户名')
    signature = models.CharField(max_length=128, blank=True, null=True, verbose_name='个性签名')
    gender = models.IntegerField(null=True, blank=True, verbose_name='性别')
    college = models.CharField(max_length=16, blank=True, null=True, verbose_name='学院')
    grade = models.CharField(max_length=16, blank=True, null=True, verbose_name='班级')
    image = models.ImageField(verbose_name='头像', upload_to='head_img', default='default.png')

    class Meta:
        verbose_name = "用户资料"  # 表名改成中文名
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

bbs/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from bbs.models import UserProfile, Post
from ckeditor_uploader.fields import RichTextUploadingFormField, RichTextUploadingField
from ckeditor.widgets import CKEditorWidget


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-material', 'placeholder': '请输入用户名'}),error_messages={'required':'不能为空'})
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input-material', 'placeholder': '密码'}),error_messages={'required':'不能为空'})

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegForm(forms.Form):
    username = forms.CharField(max_length=16,
                               min_length=3,
                               widget=forms.TextInput(
                                   attrs={'class': 'input-material', 'placeholder': '请输入3-16位的用户名'}))
    password = forms.CharField(min_length=6,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'input-material', 'placeholder': '请输入密码'}))
    password_again = forms.CharField(min_length=6,
                                     widget=forms.PasswordInput(
                                         attrs={'class': 'input-material', 'placeholder': '再输入一次密码'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次密码不一致')
        if password.isdigit():
            raise forms.ValidationError('密码过于简单')
        return password_again


class PublishForm(forms.Form):
    content = RichTextUploadingFormField(label='', config_name='publish', error_messages={'required': '内容不能为空'})

bbs/views.py
import datetime
import random

import requests
from django.urls import reverse
from lxml import etree
import time
from django.shortcuts import render, HttpResponse, redirect,get_object_or_404
from django.http import JsonResponse
from django.views.decorators.cache import cache_page
from django.utils.cache import get_cache_key
from django.core.cache import cache
from django.contrib.auth import login, logout, authenticate
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count, Q
from bbs.models import *
from comment.models import Comment
from bbs.forms import LoginForm, RegForm, PublishForm
from comment.forms import CommentForm
from rest_framework import generics
from bbs.serializers import *
from new_spider.models import News
from django.contrib.auth.decorators import login_required
# Create your views here.


class PostList(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

def index(request):
    post_list = Post.objects.all()
    notice = Notice.objects.all().first()
    all_category_list = Category.objects.all().annotate(post_count=Count('post')).order_by('-post_count')
    all_user = UserProfile.objects.all().annotate(post_count=Count('post')).order_by('-post_count')
    all_theme = Theme.objects.all().annotate(post_count=Count('post')).order_by('-post_count')
    hot_theme = all_theme[:6]
    news_list = News.objects.all()[:5]
    hot_user = all_user[:3]
    hot_category_list = all_category_list[:3]
    if request.is_ajax():
        return render(request, 'bbs/post_list.html',locals())
    return render(request, 'bbs/index.html', locals())


def acc_login(request):
    # if request.method == "POST":
    #     referer = request.POST.get('referer')
    #     print(referer)
    #     user = authenticate(username=request.POST.get('username'),
    #                         password=request.POST.get('password'))
    #     if user:
    #         login(request, user)
    #         print(referer)
    #         return redirect(referer)
    #     else:
    #         login_error = '用户名密码错误'
    #         return render(request, 'bbs/login.html',{'login_error': login_error})
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data['user']
            login(request, user)
            return redirect(request.GET.get('from', '/'), )
    else:
        login_form = LoginForm()
    return render(request, 'bbs/login.html', locals())


def acc_logout(request):
    logout(request)
    return redirect('/')


def register(request):
    if request.method == 'POST':
        reg_form = RegForm(request.POST)
        if reg_form.is_valid():
            username = reg_form.cleaned_data['username']
            password = reg_form.cleaned_data['password']
            # 创建用户
            user = User.objects.create_user(username=username, password=password)
            user_profile = UserProfile(user=user, name=username)
            user_profile.save()
            # 登录用户
            # user_login = authenticate(username=username, password=password)
            # login(request, user_login)

            return redirect('http://127.0.0.1:8000/login/?from='+request.GET.get('from'))

    else:
        reg_form = RegForm()
    return render(request, 'bbs/register.html',locals())


# 版块页
def category(request):
    category_list = Category.objects.all()
    return render(request, 'bbs/category.html', locals())


# 版块详情页
def caregorydetail(request):
    category_name = request.GET.get('name')
    theme_pk = request.GET.get('theme')
    comment = request.GET.get('comment')
    category_detail = Category.objects.get(name=category_name)
    theme_list = Theme.objects.filter(category=category_detail)
    post_list = Post.objects.filter(category_id=category_detail.pk)
    today = datetime.datetime.now()
    today_post = Post.objects.filter(category_id=category_detail.pk,created_time__year=today.year,created_time__month=today.month,created_time__day=today.day).count()
    month_post = Post.objects.filter(category_id=category_detail.pk,created_time__year=today.year,created_time__month=today.month).count()

    comment_order = 1
    comment_label = 'dropup'
    if theme_pk:
        post_list = Post.objects.filter(category_id=category_detail.pk, theme_id=theme_pk)
    elif comment == '1':
        post_list = Post.objects.filter(category_id=category_detail.pk).order_by('-comment_count')
        comment_order = 0
        comment_label = 'dropdown'
    elif comment == '0':
        post_list = Post.objects.filter(category_id=category_detail.pk).order_by('comment_count')
        comment_order = 1
        comment_label = 'dropup'
    else:
        post_list = Post.objects.filter(category_id=category_detail.pk)
    if request.is_ajax():
        if theme_pk:
            post_list = Post.objects.filter(category_id=category_detail.pk, theme_id=theme_pk)
        elif comment == '1':
            post_list = Post.objects.filter(category_id=category_detail.pk).order_by('-comment_count')
        elif comment == '0':
            post_list = Post.objects.filter(category_id=category_detail.pk).order_by('comment_count')
        else:
            post_list = Post.objects.filter(category_id=category_detail.pk)
        return render(request, 'bbs/post_list.html',locals())
    return render(request, 'bbs/caregorydetail.html', locals())


# 帖子详情页
# @cache_page(60)
def postdetail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.read_num += 1
    post.save(update_fields=['read_num'])
    post_content_type = ContentType.objects.get_for_model(post)
    comments = Comment.objects.filter(content_type=post_content_type, object_id=post_id, parent=None).order_by('-comment_time')
    data = {'content_type': post_content_type.model,'object_id': post_id,'reply_comment_id': 0}
    comment_form = CommentForm(initial=data)
    reply_form = CommentForm(initial=data)
    return render(request, 'bbs/postdetail.html', locals())


# 发表帖子
def publish(request):
    category_list = Category.objects.all()
    pubform = PublishForm()
    if request.method == 'POST':
        pubform = PublishForm(request.POST)
        if pubform.is_valid():
            content = pubform.cleaned_data['content']
        post_category = request.POST.get('post-category')
        post_theme = request.POST.get('post-theme')
        title = request.POST.get('post-title')
        post_content = request.POST.get('editor1')
        user_id = request.user.id
        cate = Category.objects.get(id=post_category)
        cate.post_num += 1
        cate.save(update_fields=['post_num'])
        post = Post()
        post.category = cate
        post.theme = Theme.objects.get(name=post_theme, category=post_category)
        post.title = title
        post.content = content
        post.author = UserProfile.objects.get(id=user_id)
        post.save()
        return redirect('/')

    return render(request, 'bbs/publish_post.html', locals())


# 版块 主题联动选择
def linked(request):
    category_id = request.GET.get('category_id')
    theme_list = Theme.objects.filter(category_id=category_id).values('name')
    # print(theme_list)
    data = {'theme_list': list(theme_list)}
    return JsonResponse(data)


def search(request):
    keyword = request.GET.get('search')
    if keyword:
        post_list = Post.objects.filter(Q(title__contains=keyword) |
                                   Q(theme__name__contains=keyword) |
                                   Q(category__name__contains=keyword))
        post_count = len(post_list)
        category_list = Category.objects.filter(Q(name__contains=keyword) |
                                                Q(brief__contains=keyword))
        cate_count = len(category_list)
        user_list = UserProfile.objects.filter(Q(name__contains=keyword))
        user_count = len(user_list)
        return render(request,'bbs/search.html', locals())


def addpost(request):
    for i in range(6):
        base_url = 'http://jianyuluntan.com/?order=&page={}'.format(i)
        response = requests.get(base_url)
        html_str = etree.HTML(response.text)
        div_list = html_str.xpath('//div[@class="col-md-9"]/div[position()>1]')
        for div in div_list:
            title = div.xpath('./div/h6/a/text()|./div/h5/a[3]/text()')[0]
            url = 'http://jianyuluntan.com'+div.xpath('./div/h6/a/@href|./div/h5/a[3]/@href')[0]
            detail = requests.get(url)
            detail_str = etree.HTML(detail.text)
            content = detail_str.xpath('string(//div[@class="zhengwen"])').strip()
            user = UserProfile.objects.first()
            category = Category.objects.get(id=4)
            theme_list = [2,3,8,9,10]
            theme = Theme.objects.get(id=random.choice(theme_list))
            post = Post()
            post.title = title
            post.content = content
            post.author = user
            post.category = category
            post.theme = theme
            post.save()
    return HttpResponse('1')

bbs/templates/bbs/caregorydetail.html
{% extends 'base.html' %}
{% load comment_tags %}
{% block category %}
active
{% endblock %}
{% block title %}
河西学院BBS站|{{ category_name }}版块
{% endblock %}
{% block style %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="ljdh">
            <ol class="breadcrumb">
                <li><a href="{% url 'index' %}">首页</a></li>
                <li><a href="{% url 'category' %}">版块信息</a></li>
                <li><span>{{ category_name }}</span></li>

            </ol>
        </div>
        <div class="row">
            <div class="col-sm-9">
                <div class="anniu">
                    <a href="{% url 'categorydetail' %}?name={{ category_name }}" class="btn btn-primary">全部</a>
                    <div class=" btn-group {{ comment_label }}">
                    <a href="{% url 'categorydetail' %}?name={{ category_name }}&comment={{ comment_order }}" id="comment_btn" class="btn btn-primary dropdown-toggle" >
                        评论量
                        <span class="caret"></span>
                    </a>

                    </div>
                    <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        主题 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        {% for theme in theme_list %}
                        <li><a href="{% url 'categorydetail' %}?name={{ category_name }}&theme={{ theme.id }}">{{ theme.name }}</a></li>
                        {% endfor %}

                    </ul>
                    </div>

                </div>

                 {% include 'bbs/post_list.html' %}

            </div>
            <div class="col-md-3">
                <a  href="{% url 'publish' %}" class="btn bg-primary btn-block" style="margin-top: 3.5em">发布帖子</a>
                <div class="card cate-card">
                    <div class="card-cont">
                        <div class="card-title">所在版块: {{ category_name }}</div>
                        <hr>
                        <div class="row" style="margin: 1em;">
                            <div class="col-md-6" style="margin-bottom: 1em;text-align: center">
                                <div>主题数</div>
                                <div>{{ category_detail.theme_set.count }}</div>
                            </div>
                            <div class="col-md-6" style="margin-bottom: 1em;text-align: center">
                                <div>帖子数</div>
                                <div>{{ category_detail.post_set.count }}</div>
                            </div>
                            <div class="col-md-6" style="text-align: center">
                                <div>今日发帖</div>
                                <div>{{ today_post }}</div>
                            </div>
                            <div class="col-md-6" style="text-align: center">
                                <div>本月发帖</div>
                                <div>{{ month_post }}</div>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}

    <script src="/static/el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({paginateOnScroll: true});</script>

{% endblock %}

bbs/templates/bbs/category.html
{% extends 'base.html' %}

{% block category %}
active
{% endblock %}
{% block title %}
河西学院BBS站|版块页面
{% endblock %}
{% block style %}
<style>
    .bs-example{
        border: 1px solid #ddd;
        padding: 1em;
        margin: 1em 0;
        border-radius: 4px;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="ljdh">
        <ol class="breadcrumb">
            <li><a href="{% url 'index' %}">首页</a></li>
            <li><a href="">版块信息</a></li>

        </ol>
    </div>
    <div class="row">
        {% for category in category_list %}
        <div class="col-md-6">
            <div class="media bs-example">
                <div class="media-left media-middle">
                    <a href="/categorydetail/?name={{ category.name }}">
                        <img class="media-object" src="/media/{{ category.image }}" alt="...">
                    </a>
                </div>
                <div class="media-body">
                    <a href="/categorydetail/?name={{ category.name }}"><h4 class="media-heading">{{ category.name }}</h4></a>
                    <p>{{ category.brief }}</p>
                    <p>
                        <span style="margin-right: 2em">主题数：{{ category.theme_set.all.count }}</span>
                        <span>帖子数：{{ category.post_set.count}}</span>
                    </p>
                    <p><a href="/categorydetail/?name={{ category.name }}" class="btn btn-info" role="button">点击进入</a> </p>
                </div>
            </div>
        </div>
        {% endfor %}



{#        {% for category in category_list %}#}
{#            <div class="col-sm-6 col-md-4">#}
{#                <div class="thumbnail">#}
{#                    <img src="/static/{{ category.image }}" alt="...">#}
{#                    <div class="caption">#}
{#                        <h3>{{ category.name }}</h3>#}
{#                        <p>{{ category.brief }}</p>#}
{#                        <p>#}
{#                            <span style="margin-right: 2em">主题数：{{ category.theme_set.all.count }}</span>#}
{#                            <span>帖子数：{{ category.post_num }}</span>#}
{#                        </p>#}
{#                        <p><a href="#" class="btn btn-primary" role="button">点击进入</a> </p>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
    </div>
</div>
{% endblock %}

bbs/templates/bbs/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>河西学院论坛|登录</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/style.default.css" id="theme-stylesheet">
      <style>
          ul{
              list-style-type: none;
          }
      </style>
  </head>
  <body>
    <div class="page login-page">
      <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
          <div class="row">
            <!-- Logo & Information Panel-->
            <div class="col-lg-6">
              <div class="info d-flex align-items-center">
                <div class="content">
                  <div class="logo">
                    <h1>欢迎登录</h1>
                  </div>
                  <p>河西学院论坛</p>
                </div>
              </div>
            </div>
            <!-- Form Panel    -->
            <div class="col-lg-6 bg-white">
              <div class="form d-flex align-items-center">
                <div class="content">
                  <form method="post" action="" class="form-validate">
                      {% csrf_token %}
                      {% for field in login_form %}
                          <div class="form-group">
                              {{ field }}

                          </div>
                      {% endfor %}
                  <div style="margin-top: -15px"><span class="text-danger pull-left" style="font-size: 10px">{{ login_form.non_field_errors}}</span></div>

                  <div><button type="submit" class="btn btn-primary">登录</button></div>

                  </form>
{#                    <div style="margin-top: -20px;">#}
{#                    	<!-- <input type="checkbox"  id="check1"/>&nbsp;<span>记住密码</span>#}
{#                    	<input type="checkbox" id="check2"/>&nbsp;<span>自动登录</span> -->#}
{#                    	<div class="custom-control custom-checkbox " style="float: right;">#}
{#											    <input type="checkbox" class="custom-control-input" id="check2" >#}
{#											    <label class="custom-control-label" for="check2">自动登录</label>#}
{#											</div>#}
{#											<div class="custom-control custom-checkbox " style="float: right;">#}
{#											    <input type="checkbox" class="custom-control-input" id="check1" >#}
{#											    <label class="custom-control-label" for="check1">记住密码&nbsp;&nbsp;</label>#}
{#											</div>#}
{#                    </div>#}
                  <br />
                  <small>没有账号?</small><a href="{% url 'register' %}" class="signup">&nbsp;注册</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="https://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.2.1/bootstrap.min.js"></script>
{#    <script src="/static/vendor/jquery-validation/jquery.validate.min.js"></script><!--表单验证-->#}
    <!-- Main File-->
    <script src="/static/bootstrap-3.3.7/js/front.js"></script>

  </body>
</html>

bbs/templates/bbs/post_list.html
{% load comment_tags %}
{% load el_pagination_tags %}
{% lazy_paginate post_list %}
{% for post in post_list %}
    <div class="card">
        <div class="card-body">
            <img src="/media/head_img/{{ post.author.image }}" alt="" class="img-circle">
            <h5 style="margin-bottom: 1em;">
                <span class="label label-warning">{{ post.category }}</span>
                <span class="label label-info" style="margin: 0 1em">{{ post.theme }}</span>
                <a href="{% url 'postdetail' post.id %}" style="font-size: 16px;" class="text-decoration-none text-overflow">{{ post.title|slice:40 }}</a>
            </h5>
            <div class="detail">
                <span class="glyphicon glyphicon-user" style="color: #7f7f7f"></span>
                <span style="margin-right: 1em">{{ post.author }}</span>
                <span style="margin-right: 1em">发表于 {{ post.created_time }}</span>
                <i class="iconfont icon-pinglun"></i>
                <span> {% get_comment_count post %}</span>
            </div>
        </div>
    </div>

    <script>
    $('.card').hover(function () {
        $(this).addClass('animated pulse');
    },
         function(){
     $(this).removeClass('animated pulse')
    }
    );

    </script>
    {% empty %}
    <h3>当前版块还没有帖子，赶紧去发一个！</h3>
{% endfor %}
{% show_more  '加载更多' '加载中' 'show-more' %}

bbs/templates/bbs/search.html
{% extends 'base.html' %}

{% block title %}
搜索
{% endblock %}
{% block style %}
    <style>
    .post>div:first-child{
        border-top: none;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid" style="min-height: 800px">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div><h3>搜索结果:</h3></div>
            <ul class="nav nav-tabs">
                <li role="presentation" class="active" id="li_post"><a href="#" onclick="post()">帖子<span class="badge" style="margin-left: 0.5em">{{ post_count }}</span></a></li>
                <li role="presentation" id="li_cate"><a href="#" onclick="cate()">版块<span class="badge" style="margin-left: 0.5em">{{ cate_count }}</span></a></li>
                <li role="presentation" id="li_user"><a href="#" onclick="user()">用户<span class="badge" style="margin-left: 0.5em">{{ user_count }}</span></a></li>
            </ul>
            <div id="post">
                {% for post in post_list %}
                <div class="panel panel-default" >
                    <div class="panel-body">
                        <h4><a href="{% url 'postdetail' post.id %}">{{ post.title }}</a></h4>
                        <div>{{ post.content|slice:100}}</div>

                    </div>
                </div>
                {% empty %}
                    <h3>没有相关内容</h3>
                {% endfor %}
            </div>

            <div id="cate" style="display: none">
                {% for category in category_list %}

                <div class="media bs-example" style="margin-top: 1em">
                    <div class="media-left media-middle">
                        <a href="/categorydetail/?name={{ category.name }}">
                            <img class="media-object" src="/media/{{ category.image }}" alt="...">
                        </a>
                    </div>
                    <div class="media-body">
                        <a href="/categorydetail/?name={{ category.name }}"><h4 class="media-heading">{{ category.name }}</h4></a>
                        <p>{{ category.brief }}</p>
                        <p>
                            <span style="margin-right: 2em">主题数：{{ category.theme_set.all.count }}</span>
                            <span>帖子数：{{ category.post_set.count}}</span>
                        </p>
                        <p><a href="/categorydetail/?name={{ category.name }}" class="btn btn-info" role="button">点击进入</a> </p>
                    </div>
                </div>
                {% empty %}
                    <h3>没有相关内容</h3>
                {% endfor %}
            </div>
            <div id="user" style="display: none">
                {% for user in user_list %}
                    <div><h4>{{ user.name }}</h4></div>
                {% empty %}
                    <h3>没有相关内容</h3>
                {% endfor %}

            </div>
        </div>


    </div>
{% endblock %}
{% block script %}
    <script>
    function post() {
        $('#li_post').addClass('active');
        $('#li_cate').removeClass('active');
        $('#li_user').removeClass('active');
        $('#post').css('display','block');
        $('#cate').css('display','none');
        $('#user').css('display','none');
    }
    function cate() {
        $('#li_post').removeClass('active');
        $('#li_cate').addClass('active');
        $('#li_user').removeClass('active');
        $('#post').css('display','none');
        $('#cate').css('display','block');
        $('#user').css('display','none');
    }
    function user() {
        $('#li_post').removeClass('active');
        $('#li_cate').removeClass('active');
        $('#li_user').addClass('active');
        $('#post').css('display','none');
        $('#cate').css('display','none');
        $('#user').css('display','block');
    }
    </script>
{% endblock %}